articles = [
    /* List of featured articles for Arts Journalism section */
    {
        link: "https://www.vanityfair.com/style/2018/04/pulitzers-lynn-nottage-play-mlimas-tale",
        title: "With Two Pulitzers to Her Name, Lynn Nottage Knows She’s Here for the Longer Journey",
        imageLink: "https://media.vanityfair.com/photos/5acfc0690c2c5233a346e8c8/master/w_960,c_limit/t-Milmas-Tale.png",
        outlet: "Vanity Fair",
        category: "Theater",
        date: "04/13/2018",
    },
    {
        link: "https://observer.com/2021/10/david-byrne-shows-us-his-and-invites-us-to-build-our-own-american-utopia/",
        title: "David Byrne Shows Us His — and Invites Us to Build Our Own — ’American Utopia’",
        imageLink: "https://observer.com/wp-content/uploads/sites/2/2021/10/AMERICAN_UTOPIA_S_0036s.jpg?resize=970,647",
        outlet: "Observer",
        category: "Theater",
        date: "10/21/2021",
    },
    {
        link: "https://brooklynrail.org/2019/04/theater/In-Pursuit-of-the-Urgently-Inexplicable-Will-Arbery-and-His-Plays",
        title: "Will Arbery: In Pursuit of the Urgently Inexplicable",
        imageLink: "https://brooklynrail-web.imgix.net/article_image/image/23673/mcentee-1.jpg?w=440&q=80&fit=max",
        outlet: "The Brooklyn Rail",
        category: "Theater",
        date: "04/04/2019",
    },
    {
        link: "https://www.washingtonpost.com/entertainment/junebug-is-still-defined-by-its-north-south-divisions-and--now-more-than-ever--the-compassion-that-transcends-them/2020/08/12/5947c5d6-d727-11ea-930e-d88518c57dcc_story.html",
        title: "‘Junebug’ is still defined by its North-South divisions and — now more than ever — the compassion that transcends them",
        imageLink: "https://www.washingtonpost.com/wp-apps/imrs.php?src=https://arc-anglerfish-washpost-prod-washpost.s3.amazonaws.com/public/HXOZIJWXHEI6VJ4IFTUGZ2ARFE.jpg&w=916",
        outlet: "The Washington Post",
        category: "Film",
        date: "08/13/2020",
    },
    {
        link: "https://www.vanityfair.com/style/2018/09/jane-anderson-glenn-close-mother-of-the-maid",
        title: "The Writer Behind Both of Glenn Close’s “Breathtaking” Performances This Year",
        imageLink: "https://media.vanityfair.com/photos/5baa6a7dd23564139e45cd09/master/w_2560%2Cc_limit/Embed-Jane-Anderson-Glenn-Close.png",
        outlet: "Vanity Fair",
        category: "Film",
        date: "09/25/2018",
    },
    {
        link: "https://www.them.us/story/where-are-hollywoods-love-letters-to-queer-kids",
        title: "Seen On Screen: Where Are Hollywood’s Love Letters to Queer Kids?",
        imageLink: "https://media.them.us/photos/5e39f092c55f9900084113d3/master/w_2560%2Cc_limit/queer-adolescent-film.jpg",
        outlet: "them",
        category: "Film",
        date: "02/04/2020",
    },
    {
        link: "https://www.them.us/story/jeff-hiller-somebody-somewhere-q-and-a",
        title: "How Jeff Hiller Smashed Gay TV Tropes on HBO’s Somebody Somewhere",
        imageLink: "https://media.them.us/photos/61f9aa83c22bd606cd67e62a/master/w_2560%2Cc_limit/jeff-hiller.jpg",
        outlet: "them",
        category: "TV",
        date: "02/04/2022",
    },
    {
        link: "https://www.them.us/story/three-tv-actors-who-queered-masculinity-sex-and-the-city-girls-friends",
        title: "Remembering Three TV Actors Who Queered Masculinity",
        imageLink: "https://media.them.us/photos/619c033f7a8211c3e6797f17/master/w_2560%2Cc_limit/tv-gay.jpg",
        outlet: "them",
        category: "TV",
        date: "11/22/2021",
    },
    {
        link: "https://observer.com/2019/06/big-little-lies-season-2-big-questions-for-season-end/",
        title: "5 Questions ‘Big Little Lies’ Season 2 Is Begging You to Ask",
        imageLink: "https://observer.com/wp-content/uploads/sites/2/2019/06/610736b5411caf78196bc1679febf7c9e98dc15079e1373abf2e0c7f1322ac7d576f1b0a4cf85d503f372471be70edeb.jpg?resize=970,647",
        outlet: "Observer",
        category: "TV",
        date: "06/19/2019",
    },
    {
        link: "https://www.travelandleisure.com/trip-ideas/colorado-ghost-town-instagram-tourists-wine-scene",
        title: "Colorado's Ghost Towns Are Taking Over Instagram Thanks to Its Booming Wine Scene, Chic Bars, and Charming Hotels",
        imageLink: "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F28%2F2021%2F08%2F11%2Fsilver-plume-colorado-CO0821.jpg&q=60",
        outlet: "Travel and Leisure",
        category: "Food and Travel",
        date: "06/19/2019",
    },
    {
        link: "https://greenpointers.com/2021/09/16/at-philomenas-cozy-vibes-scrumptious-drinks-and-infused-ice/",
        title: "At Philomena’s, Cozy Vibes, Crushable Drinks, and Infused Ice",
        imageLink: "https://i2.wp.com/greenpointers.com/app/uploads/2021/09/PickledCrudite.jpg?w=1200&ssl=1",
        outlet: "Greenpointers",
        category: "Food and Travel",
        date: "09/16/2021",
    },
    {
        link: "https://www.edgemedianetwork.com/story.php?311374",
        title: "Meet Medellín: South America's Undersung Queer Mecca",
        imageLink: "https://www.edgemedianetwork.com/display/viewimage_storyMain.php?applicationID=0&id=311374&maxwidth=700",
        outlet: "EDGE",
        category: "Food and Travel",
        date: "12/25/2021",
    },
    {
        link: "https://www.edgemedianetwork.com/story.php?ch=news&sc=aids&sc2=&id=305332",
        title: "40 Years Later: Stigma and Progress Collide Since the Onset of the AIDS Crisis",
        imageLink: "https://www.edgemedianetwork.com/display/viewimage_storyMain.php?applicationID=0&id=305332&maxwidth=700",
        outlet: "EDGE",
        category: "Queer Culture",
        date: "05/27/2021",
    },
    {
        link: "https://www.them.us/story/iconic-tv-couples-gay-in-my-mind",
        title: "These Iconic TV Couples Are Gay in My Mind",
        imageLink: "https://media.them.us/photos/61df3675132b6512bbb0028e/master/w_2560%2Cc_limit/gimm-couples-.jpg",
        outlet: "them",
        category: "Queer Culture",
        date: "01/12/2022",
    },
    {
        link: "https://www.edgemedianetwork.com/story.php?ch=style&sc=grooming&sc2=&id=302203",
        title: "Is the Fragrance Industry Finally Breaking the Gender Binary?",
        imageLink: "https://www.edgemedianetwork.com/display/viewimage_storyMain.php?applicationID=0&id=302203&maxwidth=700",
        outlet: "EDGE",
        category: "Queer Culture",
        date: "02/22/2021",
    },
    {
        link: "http://www.newnownext.com/harry-potter-queer-lgbtq-characters-jk-rowling/10/2018/",
        title: "Harry Potter and the Relentless Queerbaiting: Why Won’t the Magical Closet Be Unlocked?",
        imageLink: "http://logoonline.mtvnimages.com/uri/mgid:ao:image:logotv.com:662079?quality=0.8&format=jpg&width=1800&height=1012",
        outlet: "NewNowNext",
        category: "Books",
        date: "10/30/2018",
    },
    {
        link: "http://www.newnownext.com/when-brooklyn-queer-hugh-ryan/02/2019/",
        title: "A Borough’s History Comes Out of the Closet in “When Brooklyn Was Queer”",
        imageLink: "http://logoonline.mtvnimages.com/uri/mgid:ao:image:logotv.com:668445?quality=0.8&format=jpg&width=1800&height=1012",
        outlet: "NewNowNext",
        category: "Books",
        date: "02/22/2019",
    },
    {
        link: "https://www.bkmag.com/2017/01/10/place-st-lydias-brooklyns-progressive-church-gem/",
        title: "A Place for All at St. Lydia’s: Brooklyn’s Progressive Church Gem",
        imageLink: "https://www.bkmag.com/wp-content/uploads/2017/01/Photo1-1600x1067.jpg",
        outlet: "Brooklyn Magazine",
        category: "Faith",
        date: "01/10/2017",
    },
    {
        link: "https://www.them.us/story/the-queer-internet-and-my-church",
        title: `You Are Very Welcome Here": The Queer Internet, and My Church`,
        imageLink: "https://media.them.us/photos/5ec6d6e7d00096d0eb324157/master/w_2560%2Cc_limit/queer-internet-church.jpg",
        outlet: "them",
        category: "Faith",
        date: "05/25/2020",
    },
    {
        link: "https://brooklynrail.org/2016/09/music/all-roads-and-genres-lead-to-tigue",
        title: "All Roads (And Genres) Lead To TIGUE",
        imageLink: "https://brooklynrail-web.imgix.net/article_image/image/17464/McEntee-web1.jpg?w=440&q=80&fit=max",
        outlet: "The Brooklyn Rail",
        category: "Music and Podcasts",
        date: "01/09/2016",
    },
    {
        link: "https://observer.com/2021/06/queers-profit-off-of-straights-sperm-in-hot-white-heist/",
        title: "Queers Profit Off of Straights’ Sperm in ‘Hot White Heist’",
        imageLink: "https://observer.com/wp-content/uploads/sites/2/2021/06/Audible-Original_Hot-White-Heist_HiRes-Cover-Art.jpg?resize=970,970",
        outlet: "Observer",
        category: "Music and Podcasts",
        date: "06/18/2021",
    },
    /* end of list */
]

outletLogos = {
    "American Theater": "american-theatre.bmp",
    "Backstage": "backstage.png",
    "Boston College": "boston-college-magazine.png",
    "The Brooklyn Rail": "brooklyn-rail.png",
    "Brooklyn Magazine": "brooklyn-magazine.svg",
    "Culture Bot": "culturebot-maximum-performance.png",
    "EDGE": "edge-media-network.png",
    "Greenpointers": "greenpointers.png",
    "HowlRound": "howlround-theatre-commons.svg",
    "Holy Cross": "college-of-the-holy-cross.png",
    "Into": "into.png",
    "NewNowNext": "newnownext.jpg",
    "Observer": "observer.png",
    "Playbill": "playbill.png",
    "them": "them.png",
    "Travel and Leisure": "travel-and-leisure.png",
    "Vanity Fair": "vanity-fair.png",
    "The Washington Post": "washington-post.png",
}

outletFeaturedArticles = {
    "American Theater": "https://www.americantheatre.org/byline/billy-mcentee/",
    "Backstage": "https://www.backstage.com/magazine/article/acting-schools-coronavirus-zoom-remote-digital-70378/",
    "Boston College": "https://www.bc.edu/bc-web/bcnews/campus-community/alumni/curtain-call--eagles-on-broadway.html",
    "The Brooklyn Rail": "https://brooklynrail.org/contributor/Billy-McEntee",
    "Brooklyn Magazine": "https://www.bkmag.com/2016/10/11/brooklyn-born-playwright-jordan-seavey-gives-spotlight-homos/",
    "Culture Bot": "https://www.culturebot.org/author/billy-mcentee/",
    "EDGE": "https://www.edgemedianetwork.com/story.php?ch=style&sc=grooming&sc2=&id=302203",
    "Greenpointers": "https://greenpointers.com/author/williamm/",
    "HowlRound": "https://howlround.com/commons/billy-mcentee",
    "Holy Cross": "https://news.holycross.edu/blog/2019/07/29/theater-in-a-contentious-age-holy-cross-alumnus-uses-theater-to-tackle-contemporary-questions/",
    "Into": "https://www.intomore.com/gaming/can-match-thirst-trap-caption/",
    "NewNowNext": "http://www.newnownext.com/author/mcenteeb/",
    "Observer": "https://observer.com/author/billy-mcentee/",
    "Playbill": "https://playbill.com/article/tony-award-winner-kelli-ohara-completes-the-2021-new-york-city-marathon",
    "them": "https://www.them.us/contributor/billy-mcentee",
    "Travel and Leisure": "https://www.travelandleisure.com/trip-ideas/colorado-ghost-town-instagram-tourists-wine-scene",
    "Vanity Fair": "https://www.vanityfair.com/contributor/billy-mcentee",
    "The Washington Post": "https://www.washingtonpost.com/entertainment/junebug-is-still-defined-by-its-north-south-divisions-and--now-more-than-ever--the-compassion-that-transcends-them/2020/08/12/5947c5d6-d727-11ea-930e-d88518c57dcc_story.html",
}
